runtime: python39

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  MYSQL_USER: rofiq
  MYSQL_PASSWORD: 1234
  MYSQL_DATABASE: db101

